version: "3"
services:
  dorotheas:
    build: ./.docker
    ports:
      - 3001:3001
    volumes:
      - ./dorotheasV2:/var/www/html
    networks:
      - dorotheas-internal

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - type: bind
        source: ./.docker/images/mysql/database
        target: /var/lib/mysql_databases
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dorotheas"
    networks:
      - dorotheas-internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    ports:
      - "9001:80"
    networks:
      - dorotheas-internal

volumes:
  .:
    external: true

networks:
  dorotheas-internal:
